# Generated by Django 4.2.10 on 2024-02-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_rename_user_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_area",
                to="backend.area",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_categorie",
                to="backend.categorie",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_format",
                to="backend.format",
            ),
        ),
    ]
