# Generated by Django 4.2.10 on 2024-02-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_course_area_alter_course_categorie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area",
                to="backend.area",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorie",
                to="backend.categorie",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="format",
                to="backend.format",
            ),
        ),
    ]
