# Generated by Django 4.2.10 on 2024-02-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_completedcourse_mark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recomendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intersections", models.IntegerField()),
                (
                    "completedCourse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completedCourse",
                        to="backend.course",
                    ),
                ),
                (
                    "recomendatedCourse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recomendatedCourse",
                        to="backend.course",
                    ),
                ),
            ],
        ),
    ]
